name: zIsland
version: '${project.version}'
main: me.zeroseven.island.IslandPlugin
api-version: '1.20'
commands:
  island:
    usage: /island
  minion:
    usage: /minion <player> <type>
    description: Gives the speicified player a Minion spawner.
  mail:
    usage: /mail
  sell:
    usage: /sell <value>
    description: use this command to sell items
